# Generated by Django 4.0.2 on 2022-02-27 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(default='Profile/default.jpg', upload_to='Profile/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('information', models.TextField(max_length=500)),
                ('compony', models.CharField(blank=True, max_length=70, null=True)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='house/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='house/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='house/')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='house/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_house', to='home.profile')),
            ],
        ),
    ]
