# Generated by Django 4.0.2 on 2022-03-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_expire_time_profile_profile_premission'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_model',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house_model',
            name='status',
            field=models.CharField(blank=True, choices=[('accept', 'accept'), ('reject', 'reject')], max_length=6, null=True),
        ),
    ]
