# Generated by Django 4.0.2 on 2022-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_house_model_published_house_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_model',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('wait', 'wait')], default='wait', max_length=6),
        ),
    ]
