# Generated by Django 4.0.2 on 2022-03-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_images_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_model',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='house_model',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='house_model',
            name='picture4',
        ),
        migrations.AlterField(
            model_name='house_model',
            name='picture1',
            field=models.ImageField(blank=True, default='homedefualt.png', null=True, upload_to='house/'),
        ),
    ]
