# Generated by Django 4.0.2 on 2022-04-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_profile_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='No', max_length=6)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_like', to='home.house_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_like', to='home.profile')),
            ],
        ),
    ]
