# Generated by Django 4.0.2 on 2022-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_like_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_house',
            name='situation',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Unlike', max_length=6),
        ),
    ]
