# Generated by Django 4.0.2 on 2022-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_like_house_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_model',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='home.Profile'),
        ),
    ]
