# Generated by Django 4.0.2 on 2022-04-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_model',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_cat', to='home.category'),
        ),
    ]
